# train.py
from common import vn

def train_vanna():
    """
    This script performs the one-time "Three Pillar" training for the Vanna AI agent.
    It teaches the AI about your database schema, relevant business documentation,
    and advanced analytical query patterns, including the special "wow" question.
    """
    print("Starting Vanna training...")

    # --- Pillar 1: DDL Training ---
    print("Training on DDLs...")
    tables = ["customers", "employees", "departments", "products", "salesorders", "orderitems"]
    for table in tables:
        ddl = vn.run_sql(f"SHOW CREATE TABLE {table}").iloc[0, 1]
        vn.train(ddl=ddl)
        print(f"  - Trained on table: {table}")

    # --- Pillar 2: Documentation Training ---
    print("\nTraining on documentation...")
    vn.train(documentation="To find an employee's sales, you must join the employees table with the salesorders table on EmployeeID.")
    vn.train(documentation="The employees table contains a 'ManagerID' column, which indicates the EmployeeID of a person's manager.")
    vn.train(documentation="The price of a product is stored in the 'UnitPrice' column in the 'products' table.")
    print("  - Added business logic documentation.")

    # --- NEW: Pillar 2.5: Data Patterns Training (The "Street Smarts") ---
    # This is critical. We are teaching Vanna about the specific format of our data.
    print("\nStarting data patterns training...")
    vn.train(documentation="CustomerName columns often have a suffix like ' - 0001'. For searches on CustomerName, you should always use a LIKE query with a wildcard (%) at the end, not an exact match (=). For example, to find 'Menon Sameer Pvt Ltd', you should query WHERE CustomerName LIKE 'Menon Sameer Pvt Ltd%'.")
    vn.train(documentation="Employee names are split into FirstName and LastName columns. If a user asks for a full employee name, you must search both columns. For example, for 'Aarav Singh', you must query WHERE FirstName = 'Aarav' AND LastName = 'Singh'.")
    vn.train(documentation="Phone numbers are stored in the format '+91-XXXXXXXXXX'.")
    vn.train(documentation="Email addresses are stored in the ContactEmail column in the customers table.")
    print("  - Vanna training on data patterns completed.")

    # --- Pillar 3: Question-SQL Pair Training ---
    print("\nTraining on Question-SQL pairs...")

    # Add the "wow" question for the demo
    vn.train(
        question="Who is our highest-performing manager, measured by the total sales revenue generated by all the employees who report directly to them?",
        sql="""
            SELECT m.FirstName, m.LastName, SUM(so.TotalAmount) AS TotalSales
            FROM employees e
            JOIN employees m ON e.ManagerID = m.EmployeeID
            JOIN salesorders so ON e.EmployeeID = so.EmployeeID
            GROUP BY m.FirstName, m.LastName
            ORDER BY TotalSales DESC
            LIMIT 1;
        """
    )
    print("  - Added 'Top Performing Manager' training pair.")

    # Add other high-quality examples
    vn.train(
        question="What are the top 5 products by sales?",
        sql="SELECT p.ProductName, SUM(oi.Quantity * p.UnitPrice) AS TotalSales FROM products p JOIN orderitems oi ON p.ProductID = oi.ProductID GROUP BY p.ProductName ORDER BY TotalSales DESC LIMIT 5"
    )
    vn.train(
        question="Who are the top 5 employees by sales?",
        sql="SELECT e.FirstName, e.LastName, SUM(so.TotalAmount) AS TotalSales FROM employees e JOIN salesorders so ON e.EmployeeID = so.EmployeeID GROUP BY e.FirstName, e.LastName ORDER BY TotalSales DESC LIMIT 5"
    )
    vn.train(
        question="What is the total sales for each department?",
        sql="SELECT d.DepartmentName, SUM(so.TotalAmount) AS TotalSales FROM departments d JOIN employees e ON d.DepartmentID = e.DepartmentID JOIN salesorders so ON e.EmployeeID = so.EmployeeID GROUP BY d.DepartmentName ORDER BY TotalSales DESC"
    )
    vn.train(
        question="Which employees report to Andrew Fuller?",
        sql="""
        SELECT e.FirstName, e.LastName
        FROM employees e
        JOIN employees m ON e.ManagerID = m.EmployeeID
        WHERE m.FirstName = 'Andrew' AND m.LastName = 'Fuller';
        """
    )

    print("  - Added additional high-quality Question-SQL pairs.")

    print("\nTraining complete. The AI is now ready.")

if __name__ == '__main__':
    train_vanna()
